server:
  port: 8600
  tomcat:
    uri-encoding: utf-8

spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/,http://${eureka.instance.hostname}:7001/eureka/,http://${eureka.instance.hostname}:7002/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: zuul8600
    prefer-ip-address: true
    hostname: localhost


zuul:
  #ignored-services: microservicecloud-dept
  #prefix: /music
  #ignored-services: "*"
  #配置服务名和路径名对应关系
  routes:
    provider.serviceId: music-provider
    provider.path: /api/**
    consumer.serviceId: music-consumer
    consumer.path: /consumer/**
    adminManage.serviceId: music-adminManage
    adminManage.path: /admin/**
  servlet-path: /
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

