server:
  port: 8300

spring:
  application:
    name: music-consumer                           #对外暴漏的微服务名字
# web静态页面路径
spring.resources.static-locations: classpath:/music/

feign:
  hystrix:
    enabled: true
    #设置hystrix超时时间
    command:
      default:
        execution:
          #使用这个配置后isolation的超时配置可以去掉
          #timeout:
            #enable: false
          isolation:
            thread:
              timeoutInMilliseconds: 60000
  ribbon:
    #ribbon的超时时间一定要比hystix的小不然会一直触发ribbon的重试机制
    ReadTimeout: 60000
    ConnectTimeout: 60000

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/
      #defaultZone: http://${eureka.instance.hostname}:7000/eureka/,http://${eureka.instance.hostname}:7001/eureka/,http://${eureka.instance.hostname}:7002/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: consumer-8300
    prefer-ip-address: true     #访问路径可以显示IP地址
    hostname: localhost

